spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
    platform: h2
    h2:
      console:
        enabled: true
        path: /h2-console
  h2:
    console:
      settings:
        web-allow-others: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    export:
      prometheus:
        enabled: true
  global:
    scrape_interval: 15s
  scrape_configs:
    - job_name: 'app-login'
      metrics_path: '/actuator/prometheus'
      static_configs:
        - targets: [ 'localhost:8080' ]